### PR TITLE
Added AntiIdle settings

### PR DESCRIPTION
**Pull request by tomas-davidovic**
Hey,
Added another root for AntiIdle settings, so far only checkbox and spinner for the Gold timer.
Check it out, could use some beautifications I guess. But I did add tooltip!

T.

### CODE REVIEW

**Comment by Crazyht** [comment]
Hey, 

I think is better to expose all setting, but your checkbox for activate GoldCheck is good think. 
I dont know if your or my implementation is more efficient.

Anyway, I spent more time to understand how Git works, and less time to change code, and it will always be something gained ^^

You can make what you want with my change =) 

C.

**Comment by tomas-davidovic** [comment]
There is an issue that the changes actually are not respected by the
program, but I have no idea why or how. Need reinvestigation  :-/

T.

**Comment by Crazyht** [comment]
How are not respected ? It does not take the new values ​​without restarting or it does not save the values?

**Comment by tomas-davidovic** [comment]
It was a bug report I got yesterday from a guy who wanted to test it.
He was wrong, it works ok.

T.

**Pull request merged**
